name: crawler

on:
  # TODO enable scheduled execution
  # schedule:
  #  - cron: 0/5 * * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $GITHUB_WORKSPACE
          cat $GITHUB_WORKSPACE/sites.txt
          echo Add other actions to build,
          echo test, and deploy your project.
