on:
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Crawl information about public sites
        run: $GITHUB_WORKSPACE/crawl.sh

      # The resulting commit will not trigger another GitHub Actions Workflow run.
      # This is due to limitations set by GitHub.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update information about public sites
