on:
  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Crawl information about public sites
        run: $GITHUB_WORKSPACE/crawl.sh

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: websegura.pucelabits.org

      # The resulting commit will not trigger another GitHub Actions Workflow run.
      # This is due to limitations set by GitHub.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update information about public sites
